name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node (uses version in .nvmrc)
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Storing release version for changeset
        id: release_version
        run: echo "VALUE=$(./scripts/print_release_version.sh)" >> $GITHUB_OUTPUT
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}

      - name: Read the value
        id: read_release_version
        run: echo "::debug::v${{ steps.release_version.outputs.VALUE }}"
